"""Add new table Trades with user_id foreign key

Revision ID: 2919333068d2
Revises: f94ed3b27673
Create Date: 2026-01-20 15:00:07.761288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2919333068d2'
down_revision: Union[str, Sequence[str], None] = 'f94ed3b27673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
