"""Change tardiff_id to tariff_id

Revision ID: 391ae58c2bf7
Revises: 1bca01f6c8d7
Create Date: 2026-02-03 12:05:39.050876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391ae58c2bf7'
down_revision: Union[str, Sequence[str], None] = '1bca01f6c8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tariff_id', sa.String(), nullable=True))
    op.drop_column('payments', 'tadiff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tadiff_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('payments', 'tariff_id')
    # ### end Alembic commands ###
