"""add analytics fields and is_active

Revision ID: a10d267b2f3d
Revises: bec8d02c6e0e
Create Date: 2026-04-23 10:59:08.308847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10d267b2f3d'
down_revision: Union[str, Sequence[str], None] = 'bec8d02c6e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('close_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('pnl_percent', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('trades', 'pnl_percent')
    op.drop_column('trades', 'pnl')
    op.drop_column('trades', 'close_price')
    op.drop_column('trades', 'closed_at')
    # ### end Alembic commands ###
