"""Add new table Trades with user_id foreign key

Revision ID: b99056bcc687
Revises: 2919333068d2
Create Date: 2026-01-20 15:01:44.202534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99056bcc687'
down_revision: Union[str, Sequence[str], None] = '2919333068d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('position_side', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('take_profit_3', sa.Float(), nullable=True),
    sa.Column('sl_order_id', sa.String(), nullable=True),
    sa.Column('tp1_order_id', sa.String(), nullable=True),
    sa.Column('tp2_order_id', sa.String(), nullable=True),
    sa.Column('tp3_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
